server:
  build: .
  links:
   - db
  ports:
    - '5000:5000'
  environment:
    FLASK_APP: /taas/taas/app.py
    DATABASE_URI: db:5432

db:
  image: postgres:9.4
  ports:
    - '5432:5432'
  environment:
    POSTGRES_PASSWORD: 'mysecretpassword'
  volumes:
    - /tmp/usr/local/var/postgres:/var/lib/postgresql/data
